name: Auto Merge

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge pull request
        uses: 'actions/github-script@v6'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { pull_request } = context.payload;
            await github.pulls.merge({
              ...context.repo,
              pull_number: pull_request.number,
              merge_method: 'squash'
            });
